name: Build AAB

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android App Bundle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Generate Temporary Keystore
        run: |
          keytool -genkeypair \
            -alias temp-alias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore app/upload-key.keystore \
            -storetype PKCS12 \
            -dname "CN=Temporary, OU=Temporary, O=Temporary, L=Temp, S=Temp, C=US" \
            -storepass 'temppassword123' \
            -keypass 'temppassword123'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build AAB
        env:
          SIGNING_KEY_ALIAS: temp-alias
          SIGNING_KEY_PASSWORD: temppassword123
          SIGNING_STORE_PASSWORD: temppassword123
        run: ./gradlew bundleRelease

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab
