name: 'Debug: Generate Persistent Keystore (PKCS12)'

on:
  workflow_dispatch:

jobs:
  generate_keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate, Convert, and Display Keystore Info
        run: |
          set -ex # Exit on error, print commands

          echo "--- Step 1: Generating JKS Keystore ---"
          keytool -genkeypair \
            -alias perm-alias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 36500 \
            -keystore temp-keystore.jks \
            -dname "CN=User,O=User,C=US" \
            -storepass 'persistentpassword123' \
            -keypass 'persistentpassword123'
          
          echo "--- Verifying JKS file creation ---"
          ls -l temp-keystore.jks

          echo "--- Step 2: Converting JKS to PKCS12 ---"
          keytool -importkeystore \
            -srckeystore temp-keystore.jks \
            -destkeystore persistent-keystore.p12 \
            -deststoretype PKCS12 \
            -srcstorepass 'persistentpassword123' \
            -deststorepass 'persistentpassword123'

          echo "--- Verifying PKCS12 file creation ---"
          ls -l persistent-keystore.p12

          echo "--- Step 3: Displaying Secrets ---"
          echo "✅ Keystore generated and encoded successfully."
          echo "========================= IMPORTANT! COPY THE VALUES BELOW =========================