name: Generate Persistent Keystore (PKCS12)

on:
  workflow_dispatch:

jobs:
  generate_keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate JKS Keystore
        run: |
          keytool -genkeypair \
            -alias perm-alias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 36500 \
            -keystore temp-keystore.jks \
            -dname "CN=User,O=User,C=US" \
            -storepass 'persistentpassword123' \
            -keypass 'persistentpassword123'

      - name: Convert JKS to PKCS12
        run: |
          keytool -importkeystore \
            -srckeystore temp-keystore.jks \
            -destkeystore persistent-keystore.p12 \
            -deststoretype PKCS12 \
            -srcstorepass 'persistentpassword123' \
            -deststorepass 'persistentpassword123'

      - name: Encode Keystore to Base64 and Display Info
        run: |
          echo "✅ Keystore generated and encoded successfully."
          echo "========================= IMPORTANT! COPY THE VALUES BELOW ========================="
          echo ""
          echo "1. UPLOAD_KEYSTORE_BASE64 (Copy the entire string below this line):"
          echo "--------------------------------------------------------------------------------"
          base64 -w 0 persistent-keystore.p12
          echo ""
          echo "--------------------------------------------------------------------------------"
          echo ""
          echo "2. Other required secrets:"
          echo "   SIGNING_KEY_ALIAS: perm-alias"
          echo "   SIGNING_KEY_PASSWORD: persistentpassword123"
          echo "   SIGNING_STORE_PASSWORD: persistentpassword123"
          echo ""
          echo "===================================================================================="
          echo "🚨 SECURITY WARNING: Delete this workflow file from your repository after use! 🚨"