name: Generate Persistent Keystore

on:
  workflow_dispatch:

jobs:
  generate_keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore and Display Info
        run: |
          keytool -genkeypair -alias perm-alias -keyalg RSA -keysize 2048 -validity 36500 -keystore persistent-keystore.jks -storetype PKCS12 -dname "CN=User,O=User,C=US" -storepass 'persistentpassword123' -keypass 'persistentpassword123'
          echo "✅ Keystore generated. SAVE THE FOLLOWING VALUES in your repository's secrets."
          echo "===================================================================================="
          echo "1. UPLOAD_KEYSTORE_BASE64 (Copy the entire string below this line):"
          echo "--------------------------------------------------------------------------------"
          base64 -w 0 persistent-keystore.jks
          echo ""
          echo "--------------------------------------------------------------------------------"
          echo ""
          echo "2. Other required secrets:"
          echo "   SIGNING_KEY_ALIAS: perm-alias"
          echo "   SIGNING_KEY_PASSWORD: persistentpassword123"
          echo "   SIGNING_STORE_PASSWORD: persistentpassword123"
          echo "===================================================================================="
          echo "🚨 SECURITY WARNING: Delete this workflow file after saving the secrets! 🚨"
