name: 'Final: Generate Keystore Artifact'

on:
  workflow_dispatch:

jobs:
  generate_keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate and Convert Keystore
        run: |
          # Generate JKS Keystore
          keytool -genkeypair \
            -alias perm-alias \
            -keyalg RSA \
            -keysize 2048 \
            -validity 36500 \
            -keystore temp-keystore.jks \
            -dname "CN=User,O=User,C=US" \
            -storepass 'persistentpassword123' \
            -keypass 'persistentpassword123'

          # Convert JKS to PKCS12
          keytool -importkeystore \
            -srckeystore temp-keystore.jks \
            -destkeystore persistent-keystore.p12 \
            -deststoretype PKCS12 \
            -srcstorepass 'persistentpassword123' \
            -deststorepass 'persistentpassword123'

      - name: Create Secrets File
        run: |
          echo "Secrets for GitHub:" > secrets.txt
          echo "=======================================" >> secrets.txt
          echo "" >> secrets.txt
          echo "SIGNING_KEY_ALIAS: perm-alias" >> secrets.txt
          echo "SIGNING_KEY_PASSWORD: persistentpassword123" >> secrets.txt
          echo "SIGNING_STORE_PASSWORD: persistentpassword123" >> secrets.txt
          echo "" >> secrets.txt
          echo "--- UPLOAD_KEYSTORE_BASE64 (Copy all lines below) ---" >> secrets.txt
          base64 -w 0 persistent-keystore.p12 >> secrets.txt

      - name: Upload Keystore and Secrets as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore-secrets
          path: |
            persistent-keystore.p12
            secrets.txt
          retention-days: 1

      - name: Final Instructions
        run: |
          echo "✅ Keystore and secrets file have been uploaded as an artifact named 'keystore-secrets'."
          echo "Please download the artifact from the summary page of this workflow run."
          echo "🚨 IMPORTANT: Delete this workflow file and the downloaded artifact after use! 🚨"
