name: 'Debug v2: Generate Keystore Artifact'

on:
  workflow_dispatch:

jobs:
  generate_keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Generate, Convert, and Prepare Artifacts
        run: |
          set -ex # Exit on error, print all commands

          echo "--- Current Directory ---"
          pwd
          echo "--- Listing files before starting ---"
          ls -la

          echo "--- Step 1: Generating JKS Keystore ---"
          keytool -genkeypair \
            -alias perm-alias -keyalg RSA -keysize 2048 -validity 36500 \
            -keystore temp-keystore.jks -dname "CN=User,O=User,C=US" \
            -storepass 'persistentpassword123' -keypass 'persistentpassword123'
          echo "--- Verifying JKS file creation ---"
          ls -l temp-keystore.jks

          echo "--- Step 2: Converting JKS to PKCS12 ---"
          keytool -importkeystore \
            -srckeystore temp-keystore.jks -destkeystore persistent-keystore.p12 \
            -deststoretype PKCS12 -srcstorepass 'persistentpassword123' \
            -deststorepass 'persistentpassword123'
          echo "--- Verifying PKCS12 file creation ---"
          ls -l persistent-keystore.p12

          echo "--- Step 3: Creating secrets.txt ---"
          {
            echo "Secrets for GitHub:"
            echo "======================================="
            echo ""
            echo "SIGNING_KEY_ALIAS: perm-alias"
            echo "SIGNING_KEY_PASSWORD: persistentpassword123"
            echo "SIGNING_STORE_PASSWORD: persistentpassword123"
            echo ""
            echo "--- UPLOAD_KEYSTORE_BASE64 (Copy all lines below) ---"
            base64 -w 0 persistent-keystore.p12
          } > secrets.txt
          echo "--- Verifying secrets.txt creation ---"
          ls -l secrets.txt
          echo "--- Content of secrets.txt ---"
          cat secrets.txt

      - name: Upload Keystore and Secrets as Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: keystore-secrets
          path: |
            persistent-keystore.p12
            secrets.txt